import { NextResponse } from 'next/server'
import { getMollieClient } from '@/lib/integrations/payment-mollie'
import { requireEnvOrReturn503 } from '@/lib/route-helpers'
import { getRequestId, attachRequestId, makeRequestLogger } from '@/lib/request-id'
import { verifyMollieCancelToken } from '@/lib/mollie-manage-token'
import { handleMollieSubscriptionCanceled } from '@/lib/payment-handlers'
import { sendEmail } from '@/lib/mailer'
import { SITE_BASE_URL } from '@/lib/config'

/**
 * GET /api/mollie-manage/cancel?token=<signed-token>
 *
 * Token-gated subscription cancel endpoint. The token was generated by
 * /api/mollie-manage and emailed to the donor — it carries
 * (customerId, subscriptionId, scope='cancel') with a 7-day HMAC-signed
 * expiry. Donor clicks the link in their inbox; we verify and call
 * mollie.customers_subscriptions.cancel().
 *
 * Renders a minimal HTML success or error page so the donor sees confirmation
 * directly in the browser (no JSON dump). Owner is notified via the existing
 * handleMollieSubscriptionCanceled handler.
 *
 * Failure modes:
 *   - Missing/bad token  → 400 with "Link invalid or expired" page.
 *   - Mollie API error   → 502 with "Try again or email us" page.
 *   - Otherwise          → 200 with success page.
 */

async function fetchMollieCustomer(customerId: string, mollie: unknown): Promise<{ email: string | null; name: string | null }> {
  if (!mollie) return { email: null, name: null }
  try {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const customer = await (mollie as any).customers.get(customerId)
    return {
      email: typeof customer?.email === 'string' ? customer.email : null,
      name: typeof customer?.name === 'string' ? customer.name : null,
    }
  } catch {
    return { email: null, name: null }
  }
}

function htmlPage(title: string, body: string, status: number): NextResponse {
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>${title} — Alpacas Ibiza</title>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta name="robots" content="noindex,nofollow" />
<style>
  body{font-family:system-ui,sans-serif;background:#f9f9f9;color:#2d2d2d;margin:0;padding:48px 24px;line-height:1.5}
  main{max-width:560px;margin:0 auto;background:#fff;border-radius:12px;padding:32px;box-shadow:0 1px 4px rgba(0,0,0,.06)}
  h1{color:#556B2F;font-size:24px;margin:0 0 16px}
  a{color:#556B2F}
  .muted{color:#888;font-size:13px;margin-top:24px}
</style>
</head>
<body><main>${body}<p class="muted">Alpacas Ibiza · <a href="mailto:info@alpacasibiza.com">info@alpacasibiza.com</a> · <a href="${SITE_BASE_URL}">${SITE_BASE_URL}</a></p></main></body>
</html>`
  return new NextResponse(html, {
    status,
    headers: { 'Content-Type': 'text/html; charset=utf-8', 'Cache-Control': 'no-store' },
  })
}

export async function GET(request: Request) {
  const reqId = getRequestId(request)
  const log = makeRequestLogger('mollie-manage-cancel', reqId)

  const apiKeyGate = requireEnvOrReturn503('MOLLIE_API_KEY', 'Payment system not configured')
  if (apiKeyGate) return attachRequestId(apiKeyGate, reqId)
  const apiKey = process.env.MOLLIE_API_KEY!

  const token = new URL(request.url).searchParams.get('token')
  if (!token) {
    return attachRequestId(htmlPage('Link invalid', `<h1>Link invalid</h1><p>This cancel link is missing the token. Please request a fresh management email from the <a href="${SITE_BASE_URL}/en/adopt#manage">adoption page</a>.</p>`, 400), reqId)
  }

  const payload = verifyMollieCancelToken(token)
  if (!payload) {
    log.warn('Cancel token invalid or expired')
    return attachRequestId(htmlPage('Link expired', `<h1>This link has expired</h1><p>Cancel links are valid for 7 days. Request a fresh one from the <a href="${SITE_BASE_URL}/en/adopt#manage">adoption page</a>, or email <a href="mailto:info@alpacasibiza.com">info@alpacasibiza.com</a>.</p>`, 410), reqId)
  }

  const mollie = await getMollieClient(apiKey)
  if (!mollie) {
    log.error('mollie SDK not installed')
    return attachRequestId(htmlPage('Service unavailable', `<h1>Service temporarily unavailable</h1><p>Please try again shortly or email <a href="mailto:info@alpacasibiza.com">info@alpacasibiza.com</a>.</p>`, 503), reqId)
  }

  try {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const cancelled = await (mollie as any).customers_subscriptions.cancel({
      customerId: payload.customerId,
      id: payload.subscriptionId,
    })
    log.info('subscription canceled', { customerId: payload.customerId, subscriptionId: payload.subscriptionId })

    // Owner notification — reuse the existing handler so the email shape stays
    // consistent with subscription cancellations triggered elsewhere.
    try {
      await handleMollieSubscriptionCanceled(
        {
          id: payload.subscriptionId,
          customerId: payload.customerId,
          status: 'canceled',
          canceledAt: typeof cancelled?.canceledAt === 'string' ? cancelled.canceledAt : new Date().toISOString(),
          metadata: cancelled?.metadata ?? { product: 'adopt-a-paca' },
        },
        {
          sendEmail,
          fetchCustomer: (id) => fetchMollieCustomer(id, mollie),
          ownerEmail: process.env.CONTACT_EMAIL,
        },
      )
    } catch (notifyErr) {
      log.warn('Owner notification failed; cancel already succeeded', { err: String(notifyErr) })
    }

    return attachRequestId(htmlPage(
      'Adoption canceled',
      `<h1>Your adoption is canceled</h1>
       <p>We've stopped your monthly SEPA charge. No further payments will be taken.</p>
       <p>You'll keep any perks you've already received this year — your certificate, photoshoot, and remaining farm-tour bookings still stand.</p>
       <p>If you cancelled by mistake, just reply to this confirmation page or email <a href="mailto:info@alpacasibiza.com">info@alpacasibiza.com</a> and we'll re-enrol you.</p>`,
      200,
    ), reqId)
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err)
    log.error('Mollie subscription cancel failed', { message })
    return attachRequestId(htmlPage(
      'Cancel failed',
      `<h1>We couldn't cancel automatically</h1>
       <p>Mollie returned an error. Email <a href="mailto:info@alpacasibiza.com">info@alpacasibiza.com</a> and we'll cancel manually within 24 hours.</p>
       <p class="muted">Reference: <code>${payload.subscriptionId}</code></p>`,
      502,
    ), reqId)
  }
}
