/**
 * {{UNIT_TITLE}} — Assignment Submission SCORM Unit
 *
 * Template: assignment-unit.tsx (v1.0 — Feb 2026)
 * Generated by: /scorm scaffold {{unit_type}} --type assignment
 *
 * Features:
 *   - File upload with drag-and-drop
 *   - Backend API integration (presigned URL, upload, submit)
 *   - Polling for grading results (3s -> 10s -> 30s backoff with jitter)
 *   - Grade display with feedback HTML rendering
 *   - SCORM score writeback from grading result
 *
 * Customize:
 *   - Replace {{UNIT_TITLE}}, {{UNIT_NAME}}, {{UNIT_TYPE}} placeholders
 *   - Adjust allowed MIME types and max file size
 *   - Customize the grade display/feedback rendering
 *
 * Files to update:
 *   - src/App.tsx: Add lazy import + unitComponents entry
 *   - src/lib/types.ts: Add to UnitType union
 *   - scripts/build-scorm.ts: Add to UNITS array
 *   - Backend: Ensure /scorm/launch, /submissions/* endpoints exist
 *
 * Dependencies: Backend must have file upload + grading endpoints
 * Requires: @elevenlabs/react is NOT needed for this template
 */

import { useEffect, useState, useCallback, useRef } from 'react';
import { scorm } from '../../lib/scorm-api';
import type { Submission, GradingResult, LaunchResponse } from '../../lib/types';

const API_BASE = import.meta.env.VITE_API_URL || '';

type Screen = 'LAUNCHING' | 'UPLOAD' | 'UPLOADING' | 'READY_TO_SUBMIT' | 'WAITING' | 'RESULT' | 'DONE' | 'ERROR';

export default function {{UNIT_NAME}}() {
  const [screen, setScreen] = useState<Screen>('LAUNCHING');
  const [error, setError] = useState<string | null>(null);
  const [sessionToken, setSessionToken] = useState('');
  const [submission, setSubmission] = useState<Submission | null>(null);
  const [result, setResult] = useState<GradingResult | null>(null);
  const pollRef = useRef<number | null>(null);

  // --- Launch & SCORM Init ---
  const launch = useCallback(async () => {
    try {
      const ok = await scorm.initializeAsync(3, 500);
      if (!ok) throw new Error('SCORM initialization failed');

      const studentId = scorm.getStudentId();
      const studentName = scorm.getStudentName();
      if (!studentId) throw new Error('Could not read student identity');

      const res = await fetch(`${API_BASE}/v1/scorm/launch`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          scorm: {
            student_id: studentId,
            student_name: studentName,
            course_id: new URLSearchParams(window.location.search).get('course_id') || '{{UNIT_TYPE}}',
            unit_id: '{{UNIT_TYPE}}',
          },
          client: { app_version: '1.0.0' },
        }),
      });

      if (!res.ok) throw new Error(`Launch failed: ${res.status}`);
      const data: LaunchResponse = await res.json();
      setSessionToken(data.session_token);
      setSubmission(data.submission);

      // Route to correct screen based on existing submission status
      switch (data.submission.status) {
        case 'draft': setScreen('UPLOAD'); break;
        case 'uploaded': setScreen('READY_TO_SUBMIT'); break;
        case 'submitted': case 'queued': case 'grading':
          setScreen('WAITING'); break;
        case 'graded':
          setResult(data.submission.result);
          setScreen('RESULT'); break;
        case 'committed': setScreen('DONE'); break;
        default: setScreen('UPLOAD');
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Launch failed');
      setScreen('ERROR');
    }
  }, []);

  useEffect(() => { launch(); }, [launch]);

  // --- File Upload ---
  const handleUpload = useCallback(async (file: File) => {
    if (!submission || !sessionToken) return;
    setScreen('UPLOADING');
    try {
      // Step 1: Get presigned upload URL
      const urlRes = await fetch(`${API_BASE}/v1/submissions/${submission.submission_id}/upload-url`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${sessionToken}`,
        },
        body: JSON.stringify({ file_name: file.name, mime_type: file.type, size_bytes: file.size }),
      });
      if (!urlRes.ok) throw new Error(`Upload URL failed: ${urlRes.status}`);
      const { upload_url, file_token } = await urlRes.json();

      // Step 2: Upload file to storage
      await fetch(upload_url, { method: 'PUT', body: file, headers: { 'Content-Type': file.type } });

      // Step 3: Finalize upload
      const finalRes = await fetch(`${API_BASE}/v1/submissions/${submission.submission_id}/finalize-upload`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${sessionToken}`,
        },
        body: JSON.stringify({ file_token }),
      });
      if (!finalRes.ok) throw new Error(`Finalize failed: ${finalRes.status}`);

      setSubmission(prev => prev ? { ...prev, status: 'uploaded' } : prev);
      setScreen('READY_TO_SUBMIT');
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Upload failed');
      setScreen('ERROR');
    }
  }, [submission, sessionToken]);

  // --- Submit for Grading ---
  const handleSubmit = useCallback(async () => {
    if (!submission || !sessionToken) return;
    try {
      const res = await fetch(`${API_BASE}/v1/submissions/${submission.submission_id}/submit`, {
        method: 'POST',
        headers: { 'Authorization': `Bearer ${sessionToken}` },
      });
      if (!res.ok) throw new Error(`Submit failed: ${res.status}`);
      setScreen('WAITING');
      startPolling();
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Submit failed');
      setScreen('ERROR');
    }
  }, [submission, sessionToken]);

  // --- Polling with Backoff ---
  const startPolling = useCallback(() => {
    const delays = [3000, 3000, 3000, 10000, 10000, 30000];
    let attempt = 0;

    const poll = async () => {
      try {
        const res = await fetch(`${API_BASE}/v1/submissions/${submission?.submission_id}`, {
          headers: { 'Authorization': `Bearer ${sessionToken}` },
        });
        if (!res.ok) return;
        const data = await res.json();

        if (data.status === 'graded' && data.result) {
          setResult(data.result);
          setScreen('RESULT');
          return;
        }

        const jitter = Math.random() * 1000;
        const delay = delays[Math.min(attempt, delays.length - 1)] + jitter;
        attempt++;
        pollRef.current = window.setTimeout(poll, delay);
      } catch {
        const delay = delays[Math.min(attempt, delays.length - 1)];
        attempt++;
        pollRef.current = window.setTimeout(poll, delay);
      }
    };

    pollRef.current = window.setTimeout(poll, delays[0]);
  }, [submission, sessionToken]);

  // Cleanup polling on unmount
  useEffect(() => {
    return () => { if (pollRef.current) clearTimeout(pollRef.current); };
  }, []);

  // --- Commit Score to LMS ---
  const commitScore = useCallback(() => {
    if (!result) return;
    scorm.setScore(result.grade_percent, 0, 100);
    scorm.setStatus(result.pass_fail === 'passed' ? 'passed' : 'failed');
    scorm.commit();
    setScreen('DONE');
  }, [result]);

  // --- Render ---
  switch (screen) {
    case 'LAUNCHING':
      return (
        <div className="min-h-screen bg-white flex items-center justify-center p-6">
          <div className="text-center">
            <div className="animate-spin rounded-full h-12 w-12 border-4 border-blue-200 border-t-blue-600 mx-auto mb-4" />
            <h2 className="text-lg font-semibold text-gray-700">Initializing...</h2>
          </div>
        </div>
      );

    case 'UPLOAD':
      return (
        <div className="min-h-screen bg-white p-6">
          <div className="max-w-2xl mx-auto">
            <h1 className="text-2xl font-bold text-gray-900 mb-6">{{UNIT_TITLE}}</h1>
            <div
              className="border-2 border-dashed border-gray-300 rounded-lg p-12 text-center cursor-pointer hover:border-blue-400 transition-colors"
              onDragOver={e => e.preventDefault()}
              onDrop={e => { e.preventDefault(); const f = e.dataTransfer.files[0]; if (f) handleUpload(f); }}
              onClick={() => { const i = document.createElement('input'); i.type = 'file'; i.accept = '.pdf'; i.onchange = () => { if (i.files?.[0]) handleUpload(i.files[0]); }; i.click(); }}
            >
              <p className="text-gray-500 mb-2">Drag & drop your file here, or click to browse</p>
              <p className="text-sm text-gray-400">PDF files only, max 50MB</p>
            </div>
          </div>
        </div>
      );

    case 'UPLOADING':
      return (
        <div className="min-h-screen bg-white flex items-center justify-center p-6">
          <div className="text-center">
            <div className="animate-spin rounded-full h-12 w-12 border-4 border-blue-200 border-t-blue-600 mx-auto mb-4" />
            <h2 className="text-lg font-semibold text-gray-700">Uploading...</h2>
          </div>
        </div>
      );

    case 'READY_TO_SUBMIT':
      return (
        <div className="min-h-screen bg-white p-6">
          <div className="max-w-2xl mx-auto text-center">
            <h1 className="text-2xl font-bold text-gray-900 mb-4">File Uploaded</h1>
            <p className="text-gray-600 mb-6">Your file is ready. Click below to submit for grading.</p>
            <button onClick={handleSubmit} className="px-6 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 font-medium">
              Submit for Grading
            </button>
          </div>
        </div>
      );

    case 'WAITING':
      return (
        <div className="min-h-screen bg-white flex items-center justify-center p-6">
          <div className="text-center">
            <div className="animate-spin rounded-full h-12 w-12 border-4 border-blue-200 border-t-blue-600 mx-auto mb-4" />
            <h2 className="text-lg font-semibold text-gray-700">Grading in Progress...</h2>
            <p className="text-sm text-gray-500 mt-2">This usually takes 30-60 seconds</p>
          </div>
        </div>
      );

    case 'RESULT':
      return (
        <div className="min-h-screen bg-white p-6">
          <div className="max-w-2xl mx-auto">
            <h1 className="text-2xl font-bold text-gray-900 mb-4">Grading Complete</h1>
            {result && (
              <>
                <div className={`text-center p-6 rounded-lg mb-6 ${result.pass_fail === 'passed' ? 'bg-green-50' : 'bg-red-50'}`}>
                  <p className="text-4xl font-bold mb-2">{result.grade_percent}%</p>
                  <p className={`text-lg font-semibold ${result.pass_fail === 'passed' ? 'text-green-700' : 'text-red-700'}`}>
                    {result.pass_fail === 'passed' ? 'Passed' : 'Failed'}
                  </p>
                </div>
                {result.feedback_html && (
                  <div className="prose max-w-none mb-6" dangerouslySetInnerHTML={{ __html: result.feedback_html }} />
                )}
                <button onClick={commitScore} className="w-full py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 font-medium">
                  Record Grade in LMS
                </button>
              </>
            )}
          </div>
        </div>
      );

    case 'DONE':
      return (
        <div className="min-h-screen bg-white flex items-center justify-center p-6">
          <div className="text-center">
            <div className="inline-flex items-center justify-center w-20 h-20 rounded-full bg-green-100 mb-4">
              <svg className="h-10 w-10 text-green-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
              </svg>
            </div>
            <h2 className="text-xl font-bold text-gray-800 mb-2">Grade Recorded</h2>
            <p className="text-gray-600">Your grade has been saved. You can close this window.</p>
          </div>
        </div>
      );

    case 'ERROR':
      return (
        <div className="min-h-screen bg-white flex items-center justify-center p-6">
          <div className="max-w-md text-center">
            <h2 className="text-xl font-bold text-red-700 mb-2">Error</h2>
            <p className="text-gray-600 mb-4">{error}</p>
            <button onClick={() => window.location.reload()} className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700">
              Retry
            </button>
          </div>
        </div>
      );
  }
}
