/**
 * {{UNIT_TITLE}} SCORM Unit
 *
 * Template: base-unit.tsx (v1.0 — Feb 2026)
 * Generated by: /scorm scaffold {{unit_type}}
 *
 * Customize:
 *   - Replace {{UNIT_TITLE}} with your unit's display title
 *   - Replace {{UNIT_NAME}} with PascalCase component name
 *   - Replace {{UNIT_TYPE}} with snake_case unit type (e.g., study_guide)
 *   - Add unit-specific content in the marked section below
 *
 * Files to update after scaffolding:
 *   - src/App.tsx: Add lazy import + unitComponents entry
 *   - src/lib/types.ts: Add to UnitType union
 *   - scripts/build-scorm.ts: Add to UNITS array
 *   - (Optional) Backend router if unit needs API data
 */

import { useEffect, useState, useCallback } from 'react';
import { scorm } from '../../lib/scorm-api';

const API_BASE = import.meta.env.VITE_API_URL || '';

export default function {{UNIT_NAME}}() {
  const [initialized, setInitialized] = useState(false);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const init = useCallback(async () => {
    try {
      // Initialize SCORM API with retry (handles LMS timing issues)
      const ok = await scorm.initializeAsync(3, 500);
      if (!ok) {
        setError('Failed to connect to your learning management system. Please reload.');
        setLoading(false);
        return;
      }
      setInitialized(true);

      // Read student identity from LMS
      const studentId = scorm.getStudentId();
      const studentName = scorm.getStudentName();

      if (!studentId) {
        setError('Could not read student identity from SCORM.');
        setLoading(false);
        return;
      }

      // TODO: Fetch unit data from backend
      // const res = await fetch(`${API_BASE}/v1/your-endpoint/${studentId}`, {
      //   headers: { 'Content-Type': 'application/json' },
      // });
      // if (!res.ok) throw new Error(`API ${res.status}`);
      // const data = await res.json();

      setLoading(false);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Initialization failed');
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    init();
    return () => {
      // Cleanup: commit and finish SCORM session
      scorm.commit();
      scorm.finish();
    };
  }, [init]);

  // Mark as completed (call when student has viewed/interacted with content)
  const handleComplete = useCallback(() => {
    // For graded units, use: scorm.setScore(grade, 0, 100); scorm.setStatus('passed');
    // For non-graded units:
    scorm.setCompletionStatus('completed');
    scorm.commit();
  }, []);

  if (error) {
    return (
      <div className="min-h-screen bg-white flex items-center justify-center p-6">
        <div className="max-w-md text-center">
          <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-red-100 mb-4">
            <svg className="h-8 w-8 text-red-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z" />
            </svg>
          </div>
          <h2 className="text-xl font-bold text-gray-800 mb-2">Error</h2>
          <p className="text-gray-600 mb-4">{error}</p>
          <button
            onClick={() => window.location.reload()}
            className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
          >
            Retry
          </button>
        </div>
      </div>
    );
  }

  if (loading || !initialized) {
    return (
      <div className="min-h-screen bg-white flex items-center justify-center p-6">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-4 border-blue-200 border-t-blue-600 mx-auto mb-4" />
          <h2 className="text-lg font-semibold text-gray-700">Initializing...</h2>
          <p className="text-sm text-gray-500">Connecting to your learning management system</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-white p-6">
      <div className="max-w-4xl mx-auto">
        <h1 className="text-2xl font-bold text-gray-900 mb-6">{{UNIT_TITLE}}</h1>

        {/* ===== UNIT CONTENT GOES HERE ===== */}
        <div className="bg-gray-50 rounded-lg p-8 text-center text-gray-500">
          <p>Replace this section with your unit-specific UI</p>
        </div>
        {/* ===== END UNIT CONTENT ===== */}

        <div className="mt-8 flex justify-end">
          <button
            onClick={handleComplete}
            className="px-6 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors font-medium"
          >
            Mark Complete
          </button>
        </div>
      </div>
    </div>
  );
}
