/**
 * {{UNIT_TITLE}} — Data Viewer SCORM Unit
 *
 * Template: viewer-unit.tsx (v1.0 — Feb 2026)
 * Generated by: /scorm scaffold {{unit_type}} --type viewer
 *
 * Features:
 *   - Backend API data fetching (via backend proxy to Airtable/Supabase)
 *   - Table/card layout for data display
 *   - Loading, error, and empty states
 *   - No score writeback (viewer-only, status = completed on view)
 *
 * Customize:
 *   - Replace {{UNIT_TITLE}}, {{UNIT_NAME}}, {{UNIT_TYPE}} placeholders
 *   - Replace DataItem type with your actual data shape
 *   - Update the API endpoint in fetchData()
 *   - Customize the card/table rendering
 *
 * Files to update:
 *   - src/App.tsx: Add lazy import + unitComponents entry
 *   - src/lib/types.ts: Add to UnitType union
 *   - scripts/build-scorm.ts: Add to UNITS array
 *   - Backend: Add GET endpoint that returns the data for this view
 */

import { useState, useEffect, useCallback } from 'react';
import { scorm } from '../../lib/scorm-api';

const API_BASE = import.meta.env.VITE_API_URL || '';

// TODO: Replace with your actual data shape
interface DataItem {
  id: string;
  title: string;
  status: string;
  value: string | number;
}

export default function {{UNIT_NAME}}() {
  const [data, setData] = useState<DataItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [initialized, setInitialized] = useState(false);

  const fetchData = useCallback(async () => {
    setLoading(true);
    setError(null);

    try {
      // Initialize SCORM
      if (!initialized) {
        await scorm.initializeAsync(3, 500);
        setInitialized(true);
      }

      const studentId = scorm.getStudentId();
      if (!studentId) throw new Error('Could not read student identity from SCORM');

      // Get session token via launch
      const launchRes = await fetch(`${API_BASE}/v1/scorm/launch`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          scorm: {
            student_id: studentId,
            student_name: scorm.getStudentName(),
            course_id: new URLSearchParams(window.location.search).get('course_id') || '{{UNIT_TYPE}}',
            unit_id: '{{UNIT_TYPE}}',
          },
          client: { app_version: '1.0.0' },
        }),
      });

      let sessionToken = '';
      if (launchRes.ok) {
        const launchData = await launchRes.json();
        sessionToken = launchData.session_token;
      }

      // TODO: Update this endpoint to match your backend route
      const res = await fetch(`${API_BASE}/v1/your-endpoint/${studentId}`, {
        headers: {
          ...(sessionToken ? { Authorization: `Bearer ${sessionToken}` } : {}),
          'Content-Type': 'application/json',
        },
      });

      if (!res.ok) {
        const body = await res.text();
        throw new Error(`API ${res.status}: ${body}`);
      }

      const result = await res.json();
      setData(result.items || result);

      // Mark as completed after successful data load (viewer-only)
      scorm.setCompletionStatus('completed');
      scorm.commit();
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to load data');
    } finally {
      setLoading(false);
    }
  }, [initialized]);

  useEffect(() => {
    fetchData();
    return () => {
      scorm.commit();
      scorm.finish();
    };
  }, [fetchData]);

  if (error) {
    return (
      <div className="min-h-screen bg-white flex items-center justify-center p-6">
        <div className="max-w-md text-center">
          <h2 className="text-xl font-bold text-red-700 mb-2">Error</h2>
          <p className="text-gray-600 mb-4">{error}</p>
          <button
            onClick={fetchData}
            className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700"
          >
            Retry
          </button>
        </div>
      </div>
    );
  }

  if (loading) {
    return (
      <div className="min-h-screen bg-white flex items-center justify-center p-6">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-4 border-blue-200 border-t-blue-600 mx-auto mb-4" />
          <h2 className="text-lg font-semibold text-gray-700">Loading...</h2>
          <p className="text-sm text-gray-500">Fetching your data</p>
        </div>
      </div>
    );
  }

  if (data.length === 0) {
    return (
      <div className="min-h-screen bg-white p-6">
        <div className="max-w-4xl mx-auto">
          <h1 className="text-2xl font-bold text-gray-900 mb-6">{{UNIT_TITLE}}</h1>
          <div className="bg-gray-50 rounded-lg p-12 text-center">
            <p className="text-gray-500">No data available yet.</p>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-white p-6">
      <div className="max-w-4xl mx-auto">
        <h1 className="text-2xl font-bold text-gray-900 mb-6">{{UNIT_TITLE}}</h1>

        {/* Card grid layout — customize per unit needs */}
        <div className="grid gap-4 md:grid-cols-2">
          {data.map((item) => (
            <div key={item.id} className="border border-gray-200 rounded-lg p-4 hover:shadow-sm transition-shadow">
              <h3 className="font-semibold text-gray-800 mb-1">{item.title}</h3>
              <div className="flex justify-between items-center">
                <span className="text-sm text-gray-500">{item.status}</span>
                <span className="text-lg font-bold text-blue-600">{item.value}</span>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
