/**
 * {{UNIT_TITLE}} — Voice Tutor SCORM Unit
 *
 * Template: voice-unit.tsx (v1.0 — Feb 2026)
 * Generated by: /scorm scaffold {{unit_type}} --type voice
 *
 * Features:
 *   - ElevenLabs @elevenlabs/react Conversation component
 *   - Agent ID from backend config (per-course)
 *   - Conversation transcript capture
 *   - Session recording via backend API
 *   - Completion based on duration/exchange threshold
 *
 * Customize:
 *   - Replace {{UNIT_TITLE}}, {{UNIT_NAME}}, {{UNIT_TYPE}} placeholders
 *   - Adjust completion thresholds (minDurationSec, minExchanges)
 *   - Customize the theme color for the conversation UI
 *
 * Files to update:
 *   - src/App.tsx: Add lazy import + unitComponents entry
 *   - src/lib/types.ts: Add to UnitType union
 *   - scripts/build-scorm.ts: Add to UNITS array
 *   - Backend: Ensure voice tutor config/session endpoints exist
 *
 * Dependencies:
 *   - @elevenlabs/react must be in package.json
 *   - Backend must have Voice_Tutor_Config table with agent_id per course
 *   - Airtable must have Voice_Tutor_Sessions table for session recording
 */

import { useEffect } from 'react';
import { useVoiceTutorSession } from '../voice-shared/useVoiceTutorSession';
import { LaunchingScreen } from '../../components/LaunchingScreen';
import { PermissionScreen } from '../voice-shared/PermissionScreen';
import { ActiveConversation } from '../voice-shared/ActiveConversation';
import { VoiceTutorError } from '../voice-shared/VoiceTutorError';

// Completion thresholds — adjust per unit needs
const MIN_DURATION_SEC = 120;  // 2 minutes minimum
const MIN_EXCHANGES = 4;       // 4 back-and-forth exchanges minimum

export default function {{UNIT_NAME}}() {
  const {
    state,
    initialize,
    requestMicPermission,
    startSession,
    addMessage,
    endSession,
    continueConversation,
    startNewSession,
    finish,
    setError,
  } = useVoiceTutorSession('{{UNIT_TYPE}}');

  useEffect(() => {
    initialize();
  }, [initialize]);

  const renderScreen = () => {
    switch (state.screen) {
      case 'LAUNCHING':
        return <LaunchingScreen />;

      case 'PERMISSION_REQUEST':
        return <PermissionScreen onRequest={requestMicPermission} />;

      case 'READY':
        return state.config ? (
          <div className="min-h-screen bg-white p-6">
            <div className="max-w-2xl mx-auto text-center">
              <h1 className="text-2xl font-bold text-gray-900 mb-4">{{UNIT_TITLE}}</h1>
              <p className="text-gray-600 mb-2">{state.config.welcome_message || 'Ready to begin your voice session.'}</p>
              <p className="text-sm text-gray-500 mb-8">
                Minimum {Math.floor(MIN_DURATION_SEC / 60)} minutes or {MIN_EXCHANGES} exchanges to complete.
              </p>
              <button
                onClick={startSession}
                className="px-8 py-4 bg-blue-600 text-white rounded-xl hover:bg-blue-700 transition-colors text-lg font-medium"
              >
                Start Conversation
              </button>
            </div>
          </div>
        ) : (
          <VoiceTutorError
            error="Voice tutor is not configured for this course. Please contact your instructor."
            onRetry={() => window.location.reload()}
          />
        );

      case 'ACTIVE':
        return state.config ? (
          <ActiveConversation
            config={state.config}
            messages={state.messages}
            durationSec={state.durationSec}
            exchangeCount={state.exchangeCount}
            completionMet={state.completionMet}
            onMessage={addMessage}
            onEnd={endSession}
            onError={setError}
          />
        ) : (
          <VoiceTutorError
            error="Configuration missing. Please reload."
            onRetry={() => window.location.reload()}
          />
        );

      case 'COMPLETED':
        return (
          <div className="min-h-screen bg-white p-6">
            <div className="max-w-2xl mx-auto text-center">
              <div className="inline-flex items-center justify-center w-20 h-20 rounded-full bg-green-100 mb-4">
                <svg className="h-10 w-10 text-green-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                </svg>
              </div>
              <h2 className="text-xl font-bold text-gray-800 mb-2">Session Complete</h2>
              <p className="text-gray-600 mb-2">
                Duration: {Math.floor(state.durationSec / 60)}m {state.durationSec % 60}s | Exchanges: {state.exchangeCount}
              </p>
              <div className="flex justify-center gap-4 mt-6">
                <button onClick={continueConversation} className="px-6 py-3 border border-blue-600 text-blue-600 rounded-lg hover:bg-blue-50">
                  Continue Talking
                </button>
                <button onClick={endSession} className="px-6 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700">
                  End Session
                </button>
              </div>
            </div>
          </div>
        );

      case 'SESSION_END':
        return (
          <div className="min-h-screen bg-white p-6">
            <div className="max-w-2xl mx-auto text-center">
              <div className="inline-flex items-center justify-center w-20 h-20 rounded-full bg-green-100 mb-4">
                <svg className="h-10 w-10 text-green-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                </svg>
              </div>
              <h2 className="text-xl font-bold text-gray-800 mb-2">Session Recorded</h2>
              <p className="text-gray-600 mb-4">This unit is now marked as completed.</p>
              <div className="flex justify-center gap-4">
                <button onClick={startNewSession} className="px-6 py-3 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50">
                  New Session
                </button>
                <button onClick={finish} className="px-6 py-3 bg-gray-200 text-gray-700 rounded-lg hover:bg-gray-300">
                  Close
                </button>
              </div>
            </div>
          </div>
        );

      case 'ERROR':
        return (
          <VoiceTutorError
            error={state.error || 'An unexpected error occurred'}
            onRetry={() => window.location.reload()}
          />
        );

      default:
        return <LaunchingScreen />;
    }
  };

  return renderScreen();
}
