/**
 * Shared HTML email template pieces. All user-controlled values must already
 * be escaped by the caller (use lib/html#escapeHtml) — this module assumes
 * its inputs are either trusted or pre-escaped.
 */

import { escapeHtml } from './html.ts'

// Canonical site origin for absolute links inside email HTML. Mirrors
// SITE_BASE_URL in lib/config.ts (kept inline because email-templates.ts is
// used by node:test runs that bypass the @/ alias). Update both when the env
// fallback changes.
const SITE_BASE_URL_INLINE = (process.env.NEXT_PUBLIC_SITE_URL ?? 'https://alpacasibiza.com').replace(/\/$/, '')

const BRAND = {
    name: 'Alpacas Ibiza',
    primary: '#556B2F',
    secondary: '#f5f5dc',
}

export function emailLayout(innerHtml: string): string {
    return `
<div style="font-family:sans-serif;max-width:600px;margin:0 auto;color:#2d2d2d;padding:16px">
${innerHtml}
<hr style="border:none;border-top:1px solid #eee;margin:32px 0" />
<p style="color:#999;font-size:12px">${BRAND.name} · info@alpacasibiza.com · <a href="https://wa.me/32475586544" style="color:${BRAND.primary}">WhatsApp</a></p>
</div>
`.trim()
}

export interface ReminderInput {
    escapedName: string
    escapedTourName: string
    dateStr: string
    locale: string
    whatsappUrl?: string
    mapsUrl?: string
    weatherUrl?: string
    /** Google Calendar deep-link generated by googleCalendarUrl() — rendered as a small button if present. */
    addToCalendarUrl?: string
}

export function reminderEmailHtml({
    escapedName,
    escapedTourName,
    dateStr,
    whatsappUrl = 'https://wa.me/32475586544',
    mapsUrl = 'https://maps.google.com/?q=Alpacas+Ibiza,+San+Carlos,+Ibiza,+Spain',
    weatherUrl = 'https://www.google.com/search?q=weather+san+carlos+ibiza',
    addToCalendarUrl,
}: ReminderInput): string {
    const calendarButton = addToCalendarUrl
        ? `<div style="margin:24px 0">
  <a href="${addToCalendarUrl}" style="display:inline-block;padding:10px 20px;background:${BRAND.primary};color:#fff;text-decoration:none;border-radius:6px;font-size:14px;font-weight:600">📅 Add to Google Calendar</a>
</div>`
        : ''
    return emailLayout(`
<h2 style="color:${BRAND.primary}">Hi ${escapedName} 👋</h2>
<p>We're getting ready for <strong>${escapedTourName}</strong> on <strong>${dateStr}</strong>!</p>
${calendarButton}
<h3 style="margin-top:24px">Before you arrive</h3>
<ul style="line-height:1.6">
  <li>👕 <strong>Wear:</strong> closed shoes, the paddocks get dusty/muddy</li>
  <li>🧢 <strong>Bring:</strong> sun hat, sunscreen, water</li>
  <li>📸 <strong>Cameras:</strong> yes — tag us @alpacasibiza on Instagram</li>
  <li>🌦️ <strong>Weather:</strong> <a href="${weatherUrl}" style="color:${BRAND.primary}">check the San Carlos forecast</a></li>
</ul>
<h3 style="margin-top:24px">How to find us</h3>
<p>Rural north of Ibiza, near San Carlos. <a href="${mapsUrl}" style="color:${BRAND.primary}">Open in Google Maps</a>. Parking is free on-site.</p>
<h3 style="margin-top:24px">Need to change anything?</h3>
<p>Free cancellation up to 24h before. Message us on WhatsApp: <a href="${whatsappUrl}" style="color:${BRAND.primary}">+32 475 58 65 44</a>.</p>
<p style="margin-top:32px">See you soon 🦙</p>
`)
}

export interface ReviewRequestInput {
    escapedName: string
    escapedTourName: string
    googleReviewUrl?: string
    tripadvisorUrl?: string
    returnCode?: string
}

export function reviewRequestEmailHtml({
    escapedName,
    escapedTourName,
    googleReviewUrl = 'https://g.page/r/alpacasibiza/review',
    tripadvisorUrl = 'https://www.tripadvisor.com/UserReviewEdit-g3410459-d27056780',
    returnCode = 'RETURN10',
}: ReviewRequestInput): string {
    return emailLayout(`
<h2 style="color:${BRAND.primary}">Hi ${escapedName} 👋</h2>
<p>Thank you for visiting us for <strong>${escapedTourName}</strong>. We hope the herd made your day.</p>
<p>If you have 30 seconds, a review makes a huge difference for our small farm:</p>
<div style="text-align:center;margin:24px 0">
  <a href="${googleReviewUrl}" style="display:inline-block;margin:4px;padding:12px 24px;background:${BRAND.primary};color:#fff;text-decoration:none;border-radius:8px;font-weight:600">Review on Google</a>
  <a href="${tripadvisorUrl}" style="display:inline-block;margin:4px;padding:12px 24px;background:#00AA6C;color:#fff;text-decoration:none;border-radius:8px;font-weight:600">Review on TripAdvisor</a>
</div>
<p>Want to come back? Save 10% with code <strong>${returnCode}</strong> on your next visit.</p>
<p style="margin-top:24px">With gratitude,<br/>The ${BRAND.name} team 🦙</p>
`)
}

/** Subject-line helpers keyed by locale with English fallback. */
export function reminderSubject(locale: string): string {
    switch (locale) {
        case 'es': return '¡Nos vemos pronto! Tu visita a los alpacas 🦙'
        case 'de': return 'Wir freuen uns auf dich! Dein Alpaka-Besuch 🦙'
        default: return 'See you soon! Your alpaca visit 🦙'
    }
}

export function reviewRequestSubject(locale: string): string {
    switch (locale) {
        case 'es': return '¿Cómo fue tu visita a los alpacas? 🦙'
        case 'de': return 'Wie war dein Besuch bei den Alpakas? 🦙'
        default: return 'How were the alpacas? 🦙'
    }
}

// ── Adopt-a-Paca welcome email ──────────────────────────────────────────────

export type AdoptTier = 'monthly' | 'yearly'

export interface WelcomeAdoptionInput {
    /** HTML-escaped customer name (caller responsibility). undefined/empty → "Hi there" fallback. */
    escapedName?: string
    tier: AdoptTier
    /** 'Stripe' | 'Mollie' — surfaced in receipt. */
    processor: 'Stripe' | 'Mollie'
    /** Stripe session id / Mollie payment id — for audit reference. Optional; absent → processor-only line. */
    paymentRef?: string
    /**
     * HTML-escaped display name of the adopted alpaca (caller responsibility).
     * undefined → generic "your alpaca" copy. Resolved from
     * `metadata.alpaca` on the payment provider by findAlpacaName().
     */
    escapedAlpacaName?: string
    /**
     * When present, the email is addressed to the gift recipient rather than
     * the buyer. The welcome copy is adjusted accordingly and the personal
     * message from the sender is rendered in a blockquote.
     *
     * All values are HTML-escaped by the caller (escapeHtml).
     */
    gift?: {
        /** HTML-escaped name of the person who sent the gift. */
        fromName: string
        /** HTML-escaped personal message from the buyer. */
        message: string
    }
}

export function welcomeAdoptionSubject(tier: AdoptTier, isGift?: boolean): string {
    if (isGift) {
        return tier === 'yearly'
            ? "You've been gifted a yearly alpaca adoption"
            : "You've been gifted a monthly alpaca adoption"
    }
    return tier === 'yearly'
        ? 'Welcome to the herd — your yearly adoption is active'
        : 'Welcome to the herd — your monthly adoption is active'
}

export function welcomeAdoptionEmailHtml(opts: WelcomeAdoptionInput): string {
    const paymentLine = opts.paymentRef
        ? `Payment ref (${opts.processor}): ${opts.paymentRef}`
        : `Payment processor: ${opts.processor}`
    // When the donor chose a specific alpaca on the adopt page, name them in the
    // welcome copy. When they let us pick, fall back to "your alpaca".
    const alpacaLine = opts.escapedAlpacaName
        ? `<p style="margin-top:8px"><strong>Your adopted alpaca: ${opts.escapedAlpacaName}.</strong> We'll send a photo and intro story within a few days.</p>`
        : `<p style="margin-top:8px">We'll match you with one of the herd this week and send a photo and intro story.</p>`

    // ── Gift path: addressed to the recipient, not the buyer ─────────────────
    if (opts.gift) {
        const recipientGreeting = opts.escapedName ? `Hi ${opts.escapedName},` : 'Hi there,'
        const tierCopy = opts.tier === 'yearly'
            ? 'a yearly adoption (12 months coverage)'
            : 'a monthly adoption'
        return emailLayout(`
            <p>${recipientGreeting}</p>
            <p>You've been gifted ${tierCopy} at Es Currals Alpacas Ibiza by <strong>${opts.gift.fromName}</strong>.</p>
            <blockquote style="border-left:3px solid #556B2F;margin:16px 0;padding:12px 16px;background:#f9f5ec;color:#444;font-style:italic;">
              &ldquo;${opts.gift.message}&rdquo;
            </blockquote>
            <p>Your adoption is now active — here's what to expect:</p>
            ${alpacaLine}
            <p>Over your adoption year you'll receive:</p>
            <ul>
              <li>An adoption certificate with your sponsored alpaca's name</li>
              <li>Two complimentary farm tours during your year</li>
              <li>A welcome gift bundle (calendar, planner, herd photo)</li>
              <li>One photoshoot session with your alpaca</li>
              <li>A package of Alcaca natural fertilizer shipped each season</li>
            </ul>
            <p style="color:#888;font-size:12px;margin-top:24px">${paymentLine}</p>
        `)
    }

    // ── Standard path: addressed to the buyer ────────────────────────────────
    // Truthy check covers undefined, null, and empty string — falls back to "Hi there".
    const greeting = opts.escapedName ? `Hi ${opts.escapedName},` : 'Hi there,'
    const tierCopy = opts.tier === 'yearly'
        ? 'Your €900 yearly adoption (12 months coverage) is active.'
        : 'Your €75/month adoption is active.'
    return emailLayout(`
        <p>${greeting}</p>
        <p>Thank you for joining the herd at Es Currals Alpacas Ibiza. ${tierCopy}</p>
        ${alpacaLine}
        <p>Here's what arrives over your adoption year:</p>
        <ul>
          <li>An adoption certificate with your sponsored alpaca's name</li>
          <li>Two complimentary farm tours during your year</li>
          <li>A welcome gift bundle (calendar, planner, herd photo)</li>
          <li>One photoshoot session with your alpaca</li>
          <li>A package of Alcaca natural fertilizer shipped each season</li>
        </ul>
        <p>Separately, we'll send a follow-up email with your returning-supporter discount codes — <strong>10%</strong> off Wishfulfilling Weaving textiles and <strong>15%</strong> off Farm Shop orders. Those codes are emailed within 48 hours so they don't get lost in this welcome message.</p>
        <p style="color:#888;font-size:12px;margin-top:24px">${paymentLine}</p>
    `)
}

// ── Adopt-a-Paca discount-codes follow-up ───────────────────────────────────

export interface AdoptDiscountCodesInput {
    /** Customer display name (raw — will be HTML-escaped by this helper). Empty → "Hi there". */
    name: string
}

/**
 * Builds the discount-codes follow-up email. Reads codes from env:
 *   - ADOPT_DISCOUNT_CODE_WEAVING_10  (10% off Wishfulfilling Weaving)
 *   - ADOPT_DISCOUNT_CODE_FARMSHOP_15 (15% off Farm Shop)
 *
 * Both set → renders codes verbatim + "Your Adopt-a-Paca discount codes" subject.
 * Either unset → graceful "codes coming shortly" placeholder; never invents codes (Rule 5).
 *
 * Returns `{ subject, html }` so callers can spread it into sendEmail({ to, scheduledAt, ... }).
 */
export function buildAdoptDiscountCodesEmail(
    input: AdoptDiscountCodesInput,
): { subject: string; html: string } {
    const weavingCode = process.env.ADOPT_DISCOUNT_CODE_WEAVING_10
    const farmshopCode = process.env.ADOPT_DISCOUNT_CODE_FARMSHOP_15
    const bothSet = !!weavingCode && !!farmshopCode

    const safeName = input.name ? escapeHtml(input.name) : ''
    const greeting = safeName ? `Hi ${safeName},` : 'Hi there,'

    if (bothSet) {
        const html = emailLayout(`
            <p>${greeting}</p>
            <p>Welcome again to the herd. As promised, here are your returning-supporter discount codes:</p>
            <ul>
              <li><strong>10% off Wishfulfilling Weaving:</strong> <code>${escapeHtml(weavingCode!)}</code></li>
              <li><strong>15% off Farm Shop:</strong> <code>${escapeHtml(farmshopCode!)}</code></li>
            </ul>
            <p>These codes don't expire. Apply at checkout on the FareHarbor booking page or in the farm shop.</p>
        `)
        return {
            subject: 'Your Adopt-a-Paca discount codes 🦙',
            html,
        }
    }

    // Codes unset (or partial — treat as unset). Never invent codes per Rule 5.
    const html = emailLayout(`
        <p>${greeting}</p>
        <p>Welcome again to the herd. Your supporter discount codes will arrive shortly — we're finalising them and they'll reach you within 48 hours.</p>
        <p>In the meantime, your adoption is fully active and you can already book tours, weaving sessions, and gift orders.</p>
    `)
    return {
        subject: 'Welcome to the herd — discount codes on the way 🦙',
        html,
    }
}

// ── Newsletter double opt-in confirmation ────────────────────────────────────

/**
 * Builds the double opt-in confirmation email sent to a newsletter sign-up.
 * The subscriber is NOT yet subscribed — they confirm by clicking the link.
 *
 * @param confirmUrl      The full confirmation URL including the signed token.
 *                        Must be pre-validated as a same-origin URL by the caller.
 * @param unsubscribeUrl  Optional one-click unsubscribe URL. When provided,
 *                        appended as a CAN-SPAM / EU PECR footer.
 */
export function buildNewsletterConfirmEmail(
    confirmUrl: string,
    unsubscribeUrl?: string,
): { subject: string; html: string } {
    const siteUrl = SITE_BASE_URL_INLINE
    const unsubscribeFooter = unsubscribeUrl
        ? `<p style="color:#aaa;font-size:11px;margin-top:24px;border-top:1px solid #eee;padding-top:16px">
You're receiving this because you subscribed at <a href="${siteUrl}" style="color:#aaa">${siteUrl}</a>.
<br><a href="${unsubscribeUrl}" style="color:#aaa">Unsubscribe</a>
</p>`
        : ''
    const subject = 'Confirm your Alpacas Ibiza newsletter subscription 🦙'
    const html = emailLayout(`
<h2 style="color:${BRAND.primary}">One quick step</h2>
<p>You signed up for farm news from <strong>${BRAND.name}</strong> — seasonal herd updates, weaving stories, and island life.</p>
<p>Click the button below to confirm your subscription. This link is valid for 7 days.</p>
<div style="text-align:center;margin:32px 0">
  <a href="${confirmUrl}" style="display:inline-block;padding:14px 28px;background:${BRAND.primary};color:#fff;text-decoration:none;border-radius:8px;font-weight:600;font-size:16px">
    Confirm subscription
  </a>
</div>
<p style="color:#888;font-size:13px">If you didn't sign up for this newsletter, you can ignore this email — no action needed.</p>
<p style="color:#888;font-size:12px;margin-top:8px">Or copy this link into your browser:<br/>${confirmUrl}</p>
${unsubscribeFooter}
`)
    return { subject, html }
}

/**
 * Email containing a one-time Stripe Customer Portal link.
 *
 * Used by /api/billing-portal as a side-channel for the portal URL so the
 * response payload never differs between "subscriber" and "non-subscriber"
 * — closing the unauthenticated email-oracle enumeration vector.
 *
 * @param portalUrl  The Stripe portal session URL (already same-origin via SITE_BASE_URL).
 *                   Trusted input — generated server-side by stripe.billingPortal.sessions.create().
 */
/**
 * Email containing one-click cancel links for a donor's Mollie subscription(s).
 *
 * Mollie has no hosted billing portal — donors can't self-serve from a Mollie-
 * branded page the way Stripe Customer Portal allows. We replace that flow
 * with a token-gated cancel link: this email is the side-channel, the link
 * carries an HMAC-signed (customerId, subscriptionId) capability, and
 * /api/mollie-manage/cancel verifies + calls mollie.customers_subscriptions.cancel().
 *
 * Same email-oracle closure as the Stripe billing-portal email: response
 * shape of the request endpoint is identical for subscriber vs non-subscriber,
 * so attackers cannot enumerate via the request route.
 *
 * One entry per active subscription (donors usually have one; safe upper bound
 * is small — Mollie rate-limits us before this becomes a render-size problem).
 */
export function buildMollieManageEmail(input: {
    subscriptions: Array<{
        id: string
        amount: string
        interval: string
        statusUrl: string
        updatePaymentUrl: string
        cancelUrl: string
    }>
}): { subject: string; html: string } {
    const subject = 'Manage your Alpacas Ibiza adoption'
    const rows = input.subscriptions.map(s => `
        <div style="margin:24px 0;padding:16px;border:1px solid #eee;border-radius:8px">
            <p style="margin:0;font-size:12px;color:#888">Subscription <code>${escapeHtml(s.id)}</code></p>
            <p style="margin:6px 0 12px;font-size:16px;font-weight:600">${escapeHtml(s.amount)} every ${escapeHtml(s.interval)}</p>
            <div style="display:flex;flex-wrap:wrap;gap:8px;margin-top:8px">
                <a href="${escapeHtml(s.statusUrl)}" style="display:inline-block;padding:10px 16px;background:#556B2F;color:#fff;text-decoration:none;border-radius:6px;font-size:14px;font-weight:600">View status</a>
                <a href="${escapeHtml(s.updatePaymentUrl)}" style="display:inline-block;padding:10px 16px;background:#fff;color:#556B2F;border:1px solid #556B2F;text-decoration:none;border-radius:6px;font-size:14px;font-weight:600">Update payment method</a>
                <a href="${escapeHtml(s.cancelUrl)}" style="display:inline-block;padding:10px 16px;background:#fff;color:#a44;border:1px solid #a44;text-decoration:none;border-radius:6px;font-size:14px;font-weight:600">Cancel</a>
            </div>
            <p style="margin-top:12px;font-size:12px;color:#888">All links valid for 7 days. You can also reply to this email — we read every message.</p>
        </div>
    `).join('')
    const html = emailLayout(`
<h2 style="color:${BRAND.primary}">Manage your adoption</h2>
<p>You asked for a link to manage your Alpacas Ibiza adoption. We found the following active subscription${input.subscriptions.length === 1 ? '' : 's'} on your Mollie account:</p>
${rows}
<p style="color:#888;font-size:13px;margin-top:24px">If you didn't request this, you can ignore this email — the link does nothing once it expires.</p>
`)
    return { subject, html }
}

// ── Owner weekly MRR digest ──────────────────────────────────────────────────

export interface OwnerMrrDigestInput {
    mrr: number
    arr: number
    activeCount: number
    newCount7d: number
    canceledCount7d: number
    churnPct: number
    atRiskCount: number
    actionRequiredCount: number
    weekStart: string
    weekEnd: string
    /**
     * When true, append a "cold-start may under-report" advisory below the
     * dunning section. The dunning counters live in the per-Vercel-instance
     * memory store; a recent deploy/restart resets them. ADR 001 in-memory
     * persistence tradeoff — owner needs to know when the digest could lie.
     */
    dunningColdStartCaveat?: boolean
}

/**
 * Owner-facing weekly herd revenue digest.
 *
 * Subject: "[Alpacas Ibiza] Weekly herd revenue digest — {weekStart} to {weekEnd}"
 * Sections:
 *   1. KPI grid: MRR, ARR, active, new7d, canceled7d, churn%
 *   2. Dunning attention block: at-risk + action-required counts with link
 *
 * All values are numbers/strings computed server-side — no user-controlled
 * strings pass through here, so no escapeHtml needed.
 */
export function buildOwnerMrrDigestEmail(
    input: OwnerMrrDigestInput,
): { subject: string; html: string } {
    const { mrr, arr, activeCount, newCount7d, canceledCount7d, churnPct, atRiskCount, actionRequiredCount, weekStart, weekEnd, dunningColdStartCaveat } = input
    const subject = `[Alpacas Ibiza] Weekly herd revenue digest — ${weekStart} to ${weekEnd}`

    const kpiCell = (label: string, value: string, highlight = false) =>
        `<td style="padding:16px;text-align:center;background:${highlight ? '#fff3cd' : BRAND.secondary};border-radius:8px;min-width:100px">
          <div style="font-size:22px;font-weight:700;color:${BRAND.primary}">${value}</div>
          <div style="font-size:11px;color:#666;margin-top:4px;text-transform:uppercase;letter-spacing:0.5px">${label}</div>
        </td>`

    const dunningSection = (atRiskCount > 0 || actionRequiredCount > 0)
        ? `<div style="margin:24px 0;padding:16px;border-left:4px solid ${actionRequiredCount > 0 ? '#a44' : '#ffb300'};background:${actionRequiredCount > 0 ? '#fff3f3' : '#fff8e1'}">
            <strong style="color:${actionRequiredCount > 0 ? '#a44' : '#7a5500'}">Dunning attention needed</strong>
            <ul style="margin:8px 0;padding-left:20px;color:#444">
              ${atRiskCount > 0 ? `<li>${atRiskCount} donor${atRiskCount === 1 ? '' : 's'} at-risk (2 consecutive failures)</li>` : ''}
              ${actionRequiredCount > 0 ? `<li>${actionRequiredCount} donor${actionRequiredCount === 1 ? '' : 's'} action-required (3+ consecutive failures)</li>` : ''}
            </ul>
            <a href="${SITE_BASE_URL_INLINE}/admin/analytics/dunning" style="display:inline-block;padding:8px 16px;background:${BRAND.primary};color:#fff;text-decoration:none;border-radius:6px;font-size:13px">View dunning dashboard</a>
          </div>`
        : `<p style="color:#888;font-size:13px">No dunning issues this week.</p>`

    const html = emailLayout(`
<h2 style="color:${BRAND.primary}">Weekly herd revenue digest</h2>
<p style="color:#888;font-size:13px;margin-top:-8px">${weekStart} — ${weekEnd}</p>

<h3 style="margin-top:24px;margin-bottom:12px">This week</h3>
<table style="width:100%;border-collapse:separate;border-spacing:8px 0">
  <tr>
    ${kpiCell('MRR', `€${mrr.toFixed(2)}`)}
    ${kpiCell('ARR', `€${arr.toFixed(0)}`)}
    ${kpiCell('Active', activeCount.toString())}
  </tr>
</table>
<table style="width:100%;border-collapse:separate;border-spacing:8px 0;margin-top:8px">
  <tr>
    ${kpiCell('New (7d)', `+${newCount7d}`, newCount7d > 0)}
    ${kpiCell('Canceled (7d)', canceledCount7d > 0 ? `−${canceledCount7d}` : '0', false)}
    ${kpiCell('Churn %', `${churnPct.toFixed(1)}%`, churnPct > 5)}
  </tr>
</table>

<h3 style="margin-top:28px;margin-bottom:8px">Dunning</h3>
${dunningSection}
${dunningColdStartCaveat ? `<p style="color:#888;font-size:11px;margin-top:8px;font-style:italic">Dunning counters reset on each Vercel restart (in-memory store, ADR 001). If you deployed this week, the counts above may under-report — cross-check the Mollie dashboard.</p>` : ''}

<p style="color:#aaa;font-size:11px;margin-top:24px">Full details: <a href="https://alpacasibiza.com/admin/analytics/subscriptions" style="color:#aaa">subscriptions dashboard</a></p>
`)

    return { subject, html }
}

export function buildBillingPortalEmail(portalUrl: string): { subject: string; html: string } {
    const subject = 'Manage your Alpacas Ibiza adoption'
    const html = emailLayout(`
<h2 style="color:${BRAND.primary}">Manage your adoption</h2>
<p>You asked for a link to manage your Alpacas Ibiza adoption — here it is.</p>
<p>This link opens the secure Stripe portal where you can update your payment method, view invoices, or cancel your adoption.</p>
<div style="text-align:center;margin:32px 0">
  <a href="${portalUrl}" style="display:inline-block;padding:14px 28px;background:${BRAND.primary};color:#fff;text-decoration:none;border-radius:8px;font-weight:600;font-size:16px">
    Open subscription portal
  </a>
</div>
<p style="color:#888;font-size:13px">If you didn't request this, you can ignore this email — the link does nothing without your Stripe account.</p>
<p style="color:#888;font-size:12px;margin-top:8px">Or copy this link into your browser:<br/>${portalUrl}</p>
`)
    return { subject, html }
}

