/**
 * Shared HTML email template pieces. All user-controlled values must already
 * be escaped by the caller (use lib/html#escapeHtml) — this module assumes
 * its inputs are either trusted or pre-escaped.
 */

import { escapeHtml } from './html.ts'

const BRAND = {
    name: 'Alpacas Ibiza',
    primary: '#556B2F',
    secondary: '#f5f5dc',
}

export function emailLayout(innerHtml: string): string {
    return `
<div style="font-family:sans-serif;max-width:600px;margin:0 auto;color:#2d2d2d;padding:16px">
${innerHtml}
<hr style="border:none;border-top:1px solid #eee;margin:32px 0" />
<p style="color:#999;font-size:12px">${BRAND.name} · info@alpacasibiza.com · <a href="https://wa.me/32475586544" style="color:${BRAND.primary}">WhatsApp</a></p>
</div>
`.trim()
}

export interface ReminderInput {
    escapedName: string
    escapedTourName: string
    dateStr: string
    locale: string
    whatsappUrl?: string
    mapsUrl?: string
    weatherUrl?: string
    /** Google Calendar deep-link generated by googleCalendarUrl() — rendered as a small button if present. */
    addToCalendarUrl?: string
}

export function reminderEmailHtml({
    escapedName,
    escapedTourName,
    dateStr,
    whatsappUrl = 'https://wa.me/32475586544',
    mapsUrl = 'https://maps.google.com/?q=Alpacas+Ibiza,+San+Carlos,+Ibiza,+Spain',
    weatherUrl = 'https://www.google.com/search?q=weather+san+carlos+ibiza',
    addToCalendarUrl,
}: ReminderInput): string {
    const calendarButton = addToCalendarUrl
        ? `<div style="margin:24px 0">
  <a href="${addToCalendarUrl}" style="display:inline-block;padding:10px 20px;background:${BRAND.primary};color:#fff;text-decoration:none;border-radius:6px;font-size:14px;font-weight:600">📅 Add to Google Calendar</a>
</div>`
        : ''
    return emailLayout(`
<h2 style="color:${BRAND.primary}">Hi ${escapedName} 👋</h2>
<p>We're getting ready for <strong>${escapedTourName}</strong> on <strong>${dateStr}</strong>!</p>
${calendarButton}
<h3 style="margin-top:24px">Before you arrive</h3>
<ul style="line-height:1.6">
  <li>👕 <strong>Wear:</strong> closed shoes, the paddocks get dusty/muddy</li>
  <li>🧢 <strong>Bring:</strong> sun hat, sunscreen, water</li>
  <li>📸 <strong>Cameras:</strong> yes — tag us @alpacasibiza on Instagram</li>
  <li>🌦️ <strong>Weather:</strong> <a href="${weatherUrl}" style="color:${BRAND.primary}">check the San Carlos forecast</a></li>
</ul>
<h3 style="margin-top:24px">How to find us</h3>
<p>Rural north of Ibiza, near San Carlos. <a href="${mapsUrl}" style="color:${BRAND.primary}">Open in Google Maps</a>. Parking is free on-site.</p>
<h3 style="margin-top:24px">Need to change anything?</h3>
<p>Free cancellation up to 24h before. Message us on WhatsApp: <a href="${whatsappUrl}" style="color:${BRAND.primary}">+32 475 58 65 44</a>.</p>
<p style="margin-top:32px">See you soon 🦙</p>
`)
}

export interface ReviewRequestInput {
    escapedName: string
    escapedTourName: string
    googleReviewUrl?: string
    tripadvisorUrl?: string
    returnCode?: string
}

export function reviewRequestEmailHtml({
    escapedName,
    escapedTourName,
    googleReviewUrl = 'https://g.page/r/alpacasibiza/review',
    tripadvisorUrl = 'https://www.tripadvisor.com/UserReviewEdit-g3410459-d27056780',
    returnCode = 'RETURN10',
}: ReviewRequestInput): string {
    return emailLayout(`
<h2 style="color:${BRAND.primary}">Hi ${escapedName} 👋</h2>
<p>Thank you for visiting us for <strong>${escapedTourName}</strong>. We hope the herd made your day.</p>
<p>If you have 30 seconds, a review makes a huge difference for our small farm:</p>
<div style="text-align:center;margin:24px 0">
  <a href="${googleReviewUrl}" style="display:inline-block;margin:4px;padding:12px 24px;background:${BRAND.primary};color:#fff;text-decoration:none;border-radius:8px;font-weight:600">Review on Google</a>
  <a href="${tripadvisorUrl}" style="display:inline-block;margin:4px;padding:12px 24px;background:#00AA6C;color:#fff;text-decoration:none;border-radius:8px;font-weight:600">Review on TripAdvisor</a>
</div>
<p>Want to come back? Save 10% with code <strong>${returnCode}</strong> on your next visit.</p>
<p style="margin-top:24px">With gratitude,<br/>The ${BRAND.name} team 🦙</p>
`)
}

/** Subject-line helpers keyed by locale with English fallback. */
export function reminderSubject(locale: string): string {
    switch (locale) {
        case 'es': return '¡Nos vemos pronto! Tu visita a los alpacas 🦙'
        case 'de': return 'Wir freuen uns auf dich! Dein Alpaka-Besuch 🦙'
        default: return 'See you soon! Your alpaca visit 🦙'
    }
}

export function reviewRequestSubject(locale: string): string {
    switch (locale) {
        case 'es': return '¿Cómo fue tu visita a los alpacas? 🦙'
        case 'de': return 'Wie war dein Besuch bei den Alpakas? 🦙'
        default: return 'How were the alpacas? 🦙'
    }
}

// ── Adopt-a-Paca welcome email ──────────────────────────────────────────────

export type AdoptTier = 'monthly' | 'yearly'

export interface WelcomeAdoptionInput {
    /** HTML-escaped customer name (caller responsibility). undefined/empty → "Hi there" fallback. */
    escapedName?: string
    tier: AdoptTier
    /** 'Stripe' | 'Mollie' — surfaced in receipt. */
    processor: 'Stripe' | 'Mollie'
    /** Stripe session id / Mollie payment id — for audit reference. Optional; absent → processor-only line. */
    paymentRef?: string
    /**
     * HTML-escaped display name of the adopted alpaca (caller responsibility).
     * undefined → generic "your alpaca" copy. Resolved from
     * `metadata.alpaca` on the payment provider by findAlpacaName().
     */
    escapedAlpacaName?: string
}

export function welcomeAdoptionSubject(tier: AdoptTier): string {
    return tier === 'yearly'
        ? 'Welcome to the herd — your yearly adoption is active'
        : 'Welcome to the herd — your monthly adoption is active'
}

export function welcomeAdoptionEmailHtml(opts: WelcomeAdoptionInput): string {
    // Truthy check covers undefined, null, and empty string — falls back to "Hi there".
    const greeting = opts.escapedName ? `Hi ${opts.escapedName},` : 'Hi there,'
    const tierCopy = opts.tier === 'yearly'
        ? 'Your €900 yearly adoption (12 months coverage) is active.'
        : 'Your €75/month adoption is active.'
    const paymentLine = opts.paymentRef
        ? `Payment ref (${opts.processor}): ${opts.paymentRef}`
        : `Payment processor: ${opts.processor}`
    // When the donor chose a specific alpaca on the adopt page, name them in the
    // welcome copy. When they let us pick, fall back to "your alpaca".
    const alpacaLine = opts.escapedAlpacaName
        ? `<p style="margin-top:8px"><strong>Your adopted alpaca: ${opts.escapedAlpacaName}.</strong> We'll send a photo and intro story within a few days.</p>`
        : `<p style="margin-top:8px">We'll match you with one of the herd this week and send a photo and intro story.</p>`
    return emailLayout(`
        <p>${greeting}</p>
        <p>Thank you for joining the herd at Es Currals Alpacas Ibiza. ${tierCopy}</p>
        ${alpacaLine}
        <p>Here's what arrives over your adoption year:</p>
        <ul>
          <li>An adoption certificate with your sponsored alpaca's name</li>
          <li>Two complimentary farm tours during your year</li>
          <li>A welcome gift bundle (calendar, planner, herd photo)</li>
          <li>One photoshoot session with your alpaca</li>
          <li>A package of Alcaca natural fertilizer shipped each season</li>
        </ul>
        <p>Separately, we'll send a follow-up email with your returning-supporter discount codes — <strong>10%</strong> off Wishfulfilling Weaving textiles and <strong>15%</strong> off Farm Shop orders. Those codes are emailed within 48 hours so they don't get lost in this welcome message.</p>
        <p style="color:#888;font-size:12px;margin-top:24px">${paymentLine}</p>
    `)
}

// ── Adopt-a-Paca discount-codes follow-up ───────────────────────────────────

export interface AdoptDiscountCodesInput {
    /** Customer display name (raw — will be HTML-escaped by this helper). Empty → "Hi there". */
    name: string
}

/**
 * Builds the discount-codes follow-up email. Reads codes from env:
 *   - ADOPT_DISCOUNT_CODE_WEAVING_10  (10% off Wishfulfilling Weaving)
 *   - ADOPT_DISCOUNT_CODE_FARMSHOP_15 (15% off Farm Shop)
 *
 * Both set → renders codes verbatim + "Your Adopt-a-Paca discount codes" subject.
 * Either unset → graceful "codes coming shortly" placeholder; never invents codes (Rule 5).
 *
 * Returns `{ subject, html }` so callers can spread it into sendEmail({ to, scheduledAt, ... }).
 */
export function buildAdoptDiscountCodesEmail(
    input: AdoptDiscountCodesInput,
): { subject: string; html: string } {
    const weavingCode = process.env.ADOPT_DISCOUNT_CODE_WEAVING_10
    const farmshopCode = process.env.ADOPT_DISCOUNT_CODE_FARMSHOP_15
    const bothSet = !!weavingCode && !!farmshopCode

    const safeName = input.name ? escapeHtml(input.name) : ''
    const greeting = safeName ? `Hi ${safeName},` : 'Hi there,'

    if (bothSet) {
        const html = emailLayout(`
            <p>${greeting}</p>
            <p>Welcome again to the herd. As promised, here are your returning-supporter discount codes:</p>
            <ul>
              <li><strong>10% off Wishfulfilling Weaving:</strong> <code>${escapeHtml(weavingCode!)}</code></li>
              <li><strong>15% off Farm Shop:</strong> <code>${escapeHtml(farmshopCode!)}</code></li>
            </ul>
            <p>These codes don't expire. Apply at checkout on the FareHarbor booking page or in the farm shop.</p>
        `)
        return {
            subject: 'Your Adopt-a-Paca discount codes 🦙',
            html,
        }
    }

    // Codes unset (or partial — treat as unset). Never invent codes per Rule 5.
    const html = emailLayout(`
        <p>${greeting}</p>
        <p>Welcome again to the herd. Your supporter discount codes will arrive shortly — we're finalising them and they'll reach you within 48 hours.</p>
        <p>In the meantime, your adoption is fully active and you can already book tours, weaving sessions, and gift orders.</p>
    `)
    return {
        subject: 'Welcome to the herd — discount codes on the way 🦙',
        html,
    }
}

// ── Newsletter double opt-in confirmation ────────────────────────────────────

/**
 * Builds the double opt-in confirmation email sent to a newsletter sign-up.
 * The subscriber is NOT yet subscribed — they confirm by clicking the link.
 *
 * @param confirmUrl      The full confirmation URL including the signed token.
 *                        Must be pre-validated as a same-origin URL by the caller.
 * @param unsubscribeUrl  Optional one-click unsubscribe URL. When provided,
 *                        appended as a CAN-SPAM / EU PECR footer.
 */
export function buildNewsletterConfirmEmail(
    confirmUrl: string,
    unsubscribeUrl?: string,
): { subject: string; html: string } {
    const siteUrl = (process.env.NEXT_PUBLIC_SITE_URL ?? 'https://alpacasibiza.com').replace(/\/$/, '')
    const unsubscribeFooter = unsubscribeUrl
        ? `<p style="color:#aaa;font-size:11px;margin-top:24px;border-top:1px solid #eee;padding-top:16px">
You're receiving this because you subscribed at <a href="${siteUrl}" style="color:#aaa">${siteUrl}</a>.
<br><a href="${unsubscribeUrl}" style="color:#aaa">Unsubscribe</a>
</p>`
        : ''
    const subject = 'Confirm your Alpacas Ibiza newsletter subscription 🦙'
    const html = emailLayout(`
<h2 style="color:${BRAND.primary}">One quick step</h2>
<p>You signed up for farm news from <strong>${BRAND.name}</strong> — seasonal herd updates, weaving stories, and island life.</p>
<p>Click the button below to confirm your subscription. This link is valid for 7 days.</p>
<div style="text-align:center;margin:32px 0">
  <a href="${confirmUrl}" style="display:inline-block;padding:14px 28px;background:${BRAND.primary};color:#fff;text-decoration:none;border-radius:8px;font-weight:600;font-size:16px">
    Confirm subscription
  </a>
</div>
<p style="color:#888;font-size:13px">If you didn't sign up for this newsletter, you can ignore this email — no action needed.</p>
<p style="color:#888;font-size:12px;margin-top:8px">Or copy this link into your browser:<br/>${confirmUrl}</p>
${unsubscribeFooter}
`)
    return { subject, html }
}

/**
 * Email containing a one-time Stripe Customer Portal link.
 *
 * Used by /api/billing-portal as a side-channel for the portal URL so the
 * response payload never differs between "subscriber" and "non-subscriber"
 * — closing the unauthenticated email-oracle enumeration vector.
 *
 * @param portalUrl  The Stripe portal session URL (already same-origin via SITE_BASE_URL).
 *                   Trusted input — generated server-side by stripe.billingPortal.sessions.create().
 */
export function buildBillingPortalEmail(portalUrl: string): { subject: string; html: string } {
    const subject = 'Manage your Alpacas Ibiza adoption'
    const html = emailLayout(`
<h2 style="color:${BRAND.primary}">Manage your adoption</h2>
<p>You asked for a link to manage your Alpacas Ibiza adoption — here it is.</p>
<p>This link opens the secure Stripe portal where you can update your payment method, view invoices, or cancel your adoption.</p>
<div style="text-align:center;margin:32px 0">
  <a href="${portalUrl}" style="display:inline-block;padding:14px 28px;background:${BRAND.primary};color:#fff;text-decoration:none;border-radius:8px;font-weight:600;font-size:16px">
    Open subscription portal
  </a>
</div>
<p style="color:#888;font-size:13px">If you didn't request this, you can ignore this email — the link does nothing without your Stripe account.</p>
<p style="color:#888;font-size:12px;margin-top:8px">Or copy this link into your browser:<br/>${portalUrl}</p>
`)
    return { subject, html }
}

